PRAGMA foreign_keys=OFF;
BEGIN;
DROP TABLE IF EXISTS `CREATE TABLE `account``;
DROP TABLE IF EXISTS `CREATE TABLE `session``;
DROP TABLE IF EXISTS `CREATE TABLE `user``;
DROP TABLE IF EXISTS `CREATE TABLE `verification``;
DROP TABLE IF EXISTS `CREATE TABLE `todo``;
COMMIT;
PRAGMA foreign_keys=ON;
